use_frameworks!

platform :ios, '14.0'

target 'Home_Example' do
  pod 'Home', :path => '../'
  pod 'CoreEntities', :path => '../../CoreEntities'
  pod 'CoreBootcamp', :path => '../../CoreBootcamp'
end
